### PR TITLE
[Meta] Remove unnecessary type packages

### PR DESCRIPTION
**Pull request by redstonekasi**
I wasn't able to get the inclusion of vendetta-types to work like I expected it to yesterday evening but the extra type packages are definitely not needed.

### CODE REVIEW

**Comment by Beefers** [comment]
The types packages are necessary otherwise the IDE will not autocomplete definitions such as `@vendetta/patcher` or `@vendetta/metro/common/ReactNative`. Not having them also appears to cause peer dep isssues, but I have not confirmed this.

**Comment by redstonekasi** [comment]
image

**Comment by Beefers** [comment]
Hm. That's intriguing, since my VSCode would not show the function's arguments or, in the case of RN, any of the properties, even after several reloads.

**Review by Beefers — APPROVED** [review]
I checked again, yeah, we don't need the extra packages. My bad!

**Pull request merged**
